remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: WUSPBA Event Management Website
description: Hometeam - Senior Capstone Project Fall 2021

show_downloads: false

github:
  is_project_page: false
